### ISSUE TITLE
Passing config when using .vue

### ISSUE THREAD

**Issue by barrachri** [vue-bulma/nprogress#14]
Hello, starting from this example
```js
<template>
  <nprogress-container></nprogress-container>
</template>

<script>
import NprogressContainer from 'vue-nprogress/src/NprogressContainer'

export default {
  components: {
    NprogressContainer
  }
}
</script>
```

how can you pass a config?
Specifically I'd like to remove the spinner (`{ showSpinner: false }`)

**Comment by lethak** [comment]
You can always try to change the settings after it is created and before it is rendered

`this.$nprogress.settings.showSpinner = false`

I just tested and it seems to work

**Comment by whoisjorge** [comment]
I know that's probably not what you want to achieve, but you can always do it as hard as easy with CSS rules like: `visibility: hidden`, `opacity: 0`, or `diplay: none` on the **.spinner** class!

```css
#nprogress.spinner {
  /* Hardcore choice */
  visibility: hidden;
  opacity: 0;
  display: none;
}
```
